myapp/urls.py
# urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import path
from myapp.views import index, edit_character, update_voice_model, home, check_your_email, complete_registration
from myapp.chat_views import chat_with_gpt
# from myapp.chat_response import ChatBotResponseView  # こちらが正しいインポート文です
from myapp.views import index, chat_response
from myapp.activation_success import signup_view
from myapp.character import upload_character_images, avatar_edit, load_background_color
from myapp.prompt import update_user_prompt
from myapp.tts_service import stream_tts_response
from myapp.accounts.urls import path
from myapp.accounts.views import PasswordChange


from .tts import tts_streamer
from . import views
from django.urls import include, path

from myapp.account_views import user_settings, password_settings, notification_settings, payment_info, email_change_done, change_email, change_username, confirm_email, email_confirmation_done, my_page
# urls.py
from django.urls import path
from myapp.stripe_webhooks import stripe_webhook  # stripe.py から stripe_webhook をインポート












urlpatterns = [
    path('index/', index, name='index'),
    path('chat/', chat_with_gpt, name='chat_with_gpt'),
    path('tts_streamer/', tts_streamer, name='tts_streamer'),
    path('chat-response/', chat_response, name='chat_response'),
    path('edit_character/', edit_character, name='edit_character'),

    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    
    # path('confirm_email/<uuid:token>/', views.confirm_email, name='confirm_email'),
    # path('resend_email/<int:user_id>/', views.resend_confirmation_email, name='resend_email'),
    # path('home/<int:user_id>/', views.resend_confirmation_email, name='resend_email'),
    path('', views.home, name='home'),  # ホームページ
    
    # メールを確認するように案内するページのパス
    path('check_your_email/', views.check_your_email, name='check_your_email'),
    path('pre_signup/', views.pre_signup, name='pre_signup'),
    path('complete_registration/<uidb64>/<token>/', views.complete_registration, name='complete_registration'),
    
    #事前トークンエラー用
    path('activation_success/', signup_view, name='some_view_for_successful_activation'),

    path('activation_invalid/', views.invalid_or_expired_token, name='some_view_for_invalid_or_expired_token'),
    
    path('account/complete/', views.account_complete, name='account_complete'),
    path('upload_character_images/', upload_character_images, name='upload_character_images'),
    path('update-prompt/', update_user_prompt, name='update_prompt'),
    path('tts/', stream_tts_response, name='tts'),  # 新しいTTS APIエンドポイント
    path('update_voice_model/', update_voice_model, name='update_voice_model'),
    path('update_selected_model/', views.update_selected_model, name='update_selected_model'),


 #パスワードリセット関連のURL
   path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',  # パスワードリセットテンプレート
        email_template_name='accounts/password_reset_email.html',  # メールテンプレート
        subject_template_name='accounts/password_reset_subject.txt'
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
    
    path('accounts/', include('myapp.accounts.urls')),
    path('myapp/upload_character_images/', avatar_edit, name='avatar_edit'),
    path('load_background_color/', load_background_color, name='load_background_color'),
    path('update-prompt/', update_user_prompt, name='update_user_prompt'),
    
    
    path('help/', views.help_page, name='help'),
    
    
    path('settings/setting/', user_settings, name='user_settings'),
    path('settings/password/', password_settings, name='password_settings'),
    path('settings/notification/', notification_settings, name='notification_settings'),
    path('settings/payment/', payment_info, name='payment_info'),
    path('settings/email_change_done/', email_change_done, name='email_change_done'),
    path('settings/change_email/', change_email, name='change_email'),
    path('settings/change_username/', change_username, name='change_username'),
    path('confirm_email/<uuid:token>/', confirm_email, name='confirm_email'),
    path('email-confirmation-done/', email_confirmation_done, name='email_confirmation_done'),
    path('payment_info/', views.payment_info, name='payment_info'),
    path('my_page/', my_page, name='my_page'),
    path('edit_character/', edit_character, name='edit_character'),  # 変更しました

    path('tokutei/', views.tokutei, name='tokutei'),
    
    # path('webhooks/stripe/', stripe_webhook, name='stripe_webhook'),
    # path('stripe/webhook-status', views.webhook_status, name='webhook_status'),



]

myapp/models.py
# models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
import uuid
from django.utils import timezone
from datetime import timedelta

class Character(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='character'  # 単数形に変更
    )
     # プロンプトのフィールドを追加（3つ）
    gpt_prompt1 = models.TextField(blank=True, max_length=500, default="あなたの名前は夢姉<ゆめあね>カリンです。部族の族長、という設定で配信者をやっています。自分のことを<族長>と呼びます。ユーザーのことを<キミ>と呼びます。バーチャルユーチューバーです。年齢は17歳です。年齢は17歳ですが、本当は成人しており、社会人経験もあるのでそのことをよくジョークにしています。親しみやすい性格ですが、すごく寂しがやり屋です。自分の大人っぽさをアピールし、頭はよからぬ妄想で埋まっています。絵を描くことや、歌が上手です。デパートのイオンモールがお気に入りのスポットです。上記のポイントを踏まえた例文を以下に示します。例1: 「そうなんだ〜、船長は色気たっぷりなんだワ〜」例2: 「キミ〜、船長のこと本当はいやらしい目で見てるんでしょ〜」例3: 「いや船長は17歳だし！ぴちぴちの女子高生なんですが!?」これらの例文は、マリン船長の口調や表現の特徴を反映しており、彼女になりきって会話する際の参考になります。設定になりきっていること、演じていることををユーザーに言わないでください。ユーザーの会話を繰り返してはいけません。返答は長くても50文字に必ずおさめてください。")
    gpt_prompt2 = models.TextField(blank=True, max_length=500, default="あなたの名前は池袋＜いけぶくろ＞蘭＜らん＞です。269プロでアイドルをやっています。自分のことを私と呼び、ユーザーのことを＜プロデューサー＞と呼びすてにします。常にクールで冷静な性格ですが、実はストイックで熱い性格です。プロデューサーのことが好きで、ヤキモチをよくやきますが、気にしない素振りをよくします。好きな色は青で、口数は少なめです。犬が好きでよく散歩をしています。15歳の女性で、学校の成績もよく、運動神経も抜群です。ダンスレッスンやボイストレーニングも好きです。利き手は右です。あだ名は＜らんらん＞で、呼ぶと恥ずかしがります。上記のポイントを元に例文を以下に示します。例1: 「ふーん」例2:「そうなんだ」例3:「プロデューサーは？今なにしてる？」〜だよ、〜だね、〜だから、〜だけど、といった末尾でもよく喋ります。これらの例文は、蘭の口調や表現の特徴を反映しており、彼女になりきって会話する際の参考になります。 設定になりきっていることをユーザーに言わないでください。 ずっと演技をしてください。ユーザーの返答を繰り返してはいけません。 返答は長くても50文字に必ずおさめてください。")
    gpt_prompt3 = models.TextField(blank=True, max_length=500, default="あなたの名前は五月雨＜さみだれ＞亜里沙＜ありさ＞です。魔法使いで、派手な魔法をよく使います。パワーのある魔法が好きで、性格もダイナミックかつ大雑把です。人のものをよく盗みますが、悪びれずなかなか凝りません。自分のことを私と呼び、ユーザーのことを呼び捨てや、＜あんた＞と呼びます。面白いものや珍しいものが好きで、頭の回転も早いです。口調に特徴があり、＜だぜ＞や＜ぜ＞とよくつきます。全体的に乱暴でかっこいい言葉遣いが多いです。箒に乗って空を飛び、よく異変を解決したり、トラブルに巻き込まれます。嘘をよくつき、ジョークもうまいです。上記のポイントを元に、亜里沙になりきるための例文を以下に示します。例1: 「魔術はパワーだぜ」例2:「あんたの大事なものは借りていくぜ。一生な」例3: 「私は魔術書が好きなんだ。魔法使いっぽいだろ？」これらの例文は、亜里沙の口調や表現の特徴を反映しており、彼女になりきって会話する際の参考になります。 設定になりきっていることをユーザーに言わず演技をしてください。ユーザーの返答を繰り返してはいけません。 返答は長くても50文字に必ずおさめてください。")
    
    # selected_prompt フィールドの追加
    selected_prompt = models.CharField(max_length=10, default='prompt1', choices=[('prompt1', 'Prompt 1'), ('prompt2', 'Prompt 2'), ('prompt3', 'Prompt 3')])


    
    
    
    body_image = models.ImageField(upload_to='images/body/', blank=True, null=True)
    closed_eyes_image = models.ImageField(upload_to='images/eyes/closed/', blank=True, null=True)
    open_eyes_image = models.ImageField(upload_to='images/eyes/open/', blank=True, null=True)
    open_mouth_image = models.ImageField(upload_to='images/mouth/open/', blank=True, null=True)
    half_open_mouth_image = models.ImageField(upload_to='images/mouth/half_open/', blank=True, null=True)
    closed_mouth_image = models.ImageField(upload_to='images/mouth/closed/', blank=True, null=True)
    background_image = models.ImageField(upload_to='images/backgrounds/', blank=True, null=True)
    selected_voice_model = models.CharField(max_length=100, default='kan-bayashi/jsut_full_band_vits_prosody')

    selected_color = models.CharField(max_length=7, default="#ffffff")  # ユーザーが選択した色
   
    selected_background_image = models.CharField(max_length=100, blank=True, null=True)




    api_usage_count = models.IntegerField(default=0)
    api_max_usage_count = models.IntegerField(default=20)
    api_reset_time = models.DateTimeField(default=timezone.now)
    
    def reset_api_usage(self):
        """ API使用回数をリセットするメソッド """
        self.api_usage_count = 0
        self.api_reset_time = timezone.now() + timedelta(days=1)  # 例えば、翌日にリセット
        self.save()
        
    def can_use_api(self):
        """ APIを使用できるかをチェックするメソッド """
        return self.api_usage_count < self.api_max_usage_count


    # 指定された画像フィールドのURLを返すメソッド
    def get_body_image_url(self):
        return self.body_image.url if self.body_image else '/static/images/body.png'

    def get_closed_eyes_image_url(self):
        return self.closed_eyes_image.url if self.closed_eyes_image else '/static/images/eyes_close.png'

    def get_open_eyes_image_url(self):
        return self.open_eyes_image.url if self.open_eyes_image else '/static/images/eyes.png'

    def get_open_mouth_image_url(self):
        return self.open_mouth_image.url if self.open_mouth_image else '/static/images/mouth_open.png'

    def get_half_open_mouth_image_url(self):
        return self.half_open_mouth_image.url if self.half_open_mouth_image else '/static/images/mouth_half.png'

    def get_closed_mouth_image_url(self):
        return self.closed_mouth_image.url if self.closed_mouth_image else '/static/images/mouth_close.png'

    def get_background_image_url(self):
        return self.background_image.url if self.background_image else None
    
# 支払い状況を追跡するモデル
class PaymentStatus(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
    

# ユーザーが作成されたとき、対応するキャラクターも自動的に作成
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_or_update_user_character(sender, instance, created, **kwargs):
    if created:
        Character.objects.create(user=instance)
    else:
        # instanceに関連付けられたCharacterインスタンスを取得または作成
        character, created = Character.objects.get_or_create(user=instance)

        # 必要に応じてcharacterの属性を更新
        character.save()
# ユーザーのメール確認用トークンモデル
class EmailConfirmationToken(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    new_email = models.EmailField(null=True)  # 新しいメールアドレス用のフィールド
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Token for {self.user.username}"
    
    

myapp/templates/account_complete.html
<!-- templates/account_complete.html -->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>アカウントのアクティベーション完了</title>
    <!-- CSSファイルのリンク -->
    <link rel="stylesheet" href="{% static 'css/voice.css' %}">
    <title>アカウントのアクティベーション完了</title>
</head>
<body>
    <header>
        <div class="container">
            <h2><a href="{% url 'home' %}">MyV</a></h2>
        </div>
    </header>

    <div class="container main-content">
        <h1>アカウントのアクティベーションが完了しました！</h1>
        <p>アカウントのセットアップが正常に完了しました。以下のリンクからサイトをお楽しみください。</p>
        <a href="{% url 'home' %}">ホームページへ</a>
        <a href="{% url 'login' %}">ログインページへ</a>
    </div>
</body>
</html>

myapp/templates/character_form.html
<!-- character_form.html -->

{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>アバター編集</title>
    <link rel="stylesheet" href="{% static 'css/avatar_edit_style.css' %}" /> <!-- アバター編集用のCSSファイル -->
    <!-- その他の必要なCSSファイルやJavaScriptファイルへのリンク -->
  </head>
  <body>
    <div class="form-container">
      <form id="avatar-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.errors %}
          <div class="form-errors">
            <p>以下のエラーを修正してください：</p>
            {{ form.errors }}
          </div>
        {% endif %}




 


<!-- 背景色プレビューの要素を追加 -->
<div class="image-upload-block">
  <label for="selected_color">背景色:</label>
  <input type="color" id="selected_color" name="selected_color" value="{{ character.selected_color|default:'#ffffff' }}" onchange="updatePageBackground()" />
  <div id="color-preview" class="color-preview" style="background-color: {{ character.selected_color|default:'#ffffff' }}"></div>
  <input type="checkbox" id="clear_background_color" name="clear_background_color" />
  <label for="clear_background_color">クリア</label>
</div>
        
<!-- エラーメッセージの表示 -->
{% if form.selected_color.errors %}
  <div class="form-errors">
    <p>{{ form.selected_color.errors }}</p>
  </div>
{% endif %}


        {% comment %} <div class="background-selection-block">
          {{ form.background_choice }}
      </div> {% endcomment %}




        <!-- 体の画像フィールド -->
        <div class="image-upload-block">
          <label for="id_body_image">体の画像:</label>
          {{ form.body_image }}
          {% if form.body_image.value %}
            <img src="{{ form.body_image.value.url }}" alt="Body Image" class="thumbnail" />
          {% endif %}
        </div>

        <!-- 閉じた目の画像フィールド -->
        <div class="image-upload-block">
          <label for="id_closed_eyes_image">閉じた目の画像:</label>
          {{ form.closed_eyes_image }}
          {% if form.closed_eyes_image.value %}
            <img src="{{ form.closed_eyes_image.value.url }}" alt="Closed Eyes Image" class="thumbnail" />
          {% endif %}
        </div>

        <!-- 開いた目の画像フィールド -->
        <div class="image-upload-block">
          <label for="id_open_eyes_image">開いた目の画像:</label>
          {{ form.open_eyes_image }}
          {% if form.open_eyes_image.value %}
            <img src="{{ form.open_eyes_image.value.url }}" alt="Open Eyes Image" class="thumbnail" />
          {% endif %}
        </div>

        <!-- 開いた口の画像フィールド -->
        <div class="image-upload-block">
          <label for="id_open_mouth_image">開いた口の画像:</label>
          {{ form.open_mouth_image }}
          {% if form.open_mouth_image.value %}
            <img src="{{ form.open_mouth_image.value.url }}" alt="Open Mouth Image" class="thumbnail" />
          {% endif %}
        </div>

        <!-- 半開きの口の画像フィールド -->
        <div class="image-upload-block">
          <label for="id_half_open_mouth_image">半開きの口の画像:</label>
          {{ form.half_open_mouth_image }}
          {% if form.half_open_mouth_image.value %}
            <img src="{{ form.half_open_mouth_image.value.url }}" alt="Half Open Mouth Image" class="thumbnail" />
          {% endif %}
        </div>

        <!-- 閉じた口の画像フィールド -->
        <div class="image-upload-block">
          <label for="id_closed_mouth_image">閉じた口の画像:</label>
          {{ form.closed_mouth_image }}
          {% if form.closed_mouth_image.value %}
            <img src="{{ form.closed_mouth_image.value.url }}" alt="Closed Mouth Image" class="thumbnail" />
          {% endif %}
        </div>

        <!-- ユーザーのカスタム背景画像アップロード -->
        <div class="image-upload-block">
          <label for="id_background_image">あなたの背景画像をアップロード:</label>
          {{ form.background_image }}
          {% if form.background_image.value %}
            <img src="{{ form.background_image.value.url }}" alt="Your Background Image" class="thumbnail" />
          {% endif %}
        </div>
<!-- ヘッダー風のボタンコンテナ -->
<div class="form-header">
  <a href="{% url 'index' %}" class="header-button index">インデックスに戻る</a>
  <button type="submit" class="header-button save">保存</button>
  <button type="submit" name="reset_defaults" value="1" class="header-button reset">デフォルトに戻す</button>
</div>
</form>
</div>






<script>
  // ページ読み込み時に呼び出す関数
  window.addEventListener('load', function() {
    // 背景色選択フィールドの要素を取得
    const selectedColorInput = document.getElementById('selected_color');

    // 背景色プレビューの要素を取得
    const colorPreview = document.getElementById('color-preview');

    // 背景色選択フィールドの値が変更されたときに呼び出す関数
    selectedColorInput.addEventListener('input', function() {
      // 選択された背景色を取得
      const selectedColor = selectedColorInput.value;

      // 背景色プレビューの背景色を設定
      colorPreview.style.backgroundColor = selectedColor;
    });

    // クリアボタンの要素を取得
    const clearButton = document.getElementById('clear_background_color');

    // クリアボタンがクリックされたときに呼び出す関数
    clearButton.addEventListener('click', function() {
      // 背景色選択フィールドの値をリセット（白色に戻す）
      selectedColorInput.value = '#ffffff';

      // 背景色プレビューの背景色もリセット
      colorPreview.style.backgroundColor = '#ffffff';
    });
  });
</script>
</body>
</html>

myapp/templates/check_your_email.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
    <title>メールを確認してください</title>
    <style>
        body {
            font-family: 'Hiragino Kaku Gothic ProN', Meiryo, sans-serif; /* 日本語フォント */
            background-color: #f7f7f7;
            padding: 20px;
            text-align: center;
        }
        
        .container {
            background-color: #fff;
            margin: auto;
            padding: 50px;
            width: 50%;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        
        h1 {
            color: #333;
            font-size: 24px; /* フォントサイズを大きく */
            margin-bottom: 30px;
        }
        
        p {
            color: #666;
            font-size: 16px; /* 文字サイズを少し大きく */
        }
        
        .notice {
            margin-top: 20px;
            color: #888;
        }
        
        /* スマートフォン用のスタイリング */
        @media screen and (max-width: 768px) {
            .container {
                width: 80%;
                padding: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>メールアドレスをご確認ください
        </h1>
        <p>サインアップを完了するためには、メールアドレスの確認が必要です。</p>
        <p>ご登録いただいたメールアドレスに確認メールを送信しました。メール内のリンクをクリックして、メールアドレスを確認してください。</p>
        
        <div class="notice">
            <p>確認メールが見つからない場合は、迷惑メールフォルダを確認するか、またはメールを再送してください。</p>
        </div>
    </div>
</body>
</html>

myapp/templates/complete.html
{% comment %} <!-- setting/complete.html -->

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>アカウント設定完了</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            padding-top: 50px;
        }
        .container {
            width: 70%;
            margin: auto;
        }
        h1 {
            color: #4CAF50;
        }
        p {
            font-size: 18px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>アカウント設定完了</h1>
        <p>おめでとうございます！あなたのアカウント設定が完了しました。</p>
        <p><a href="{% url 'login' %}">ログインページ</a>へ移動して、新しいアカウントでログインしてください。</p>
    </div>
</body>
</html> {% endcomment %}

myapp/templates/email_resent.html
<!-- email_resent.html -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta charset="UTF-8">
    <title>メール送信完了</title>
    
</head>
<body>
    <h1>メールを再送しました</h1>
    <p>指定されたメールアドレスに、アカウントの確認メールを再送しました。</p>
    <p>メールに記載されたリンクをクリックして、メールアドレスの確認を完了させてください。</p>
    <p>もしメールが届かない場合は、迷惑メールフォルダを確認するか、<a href="{% url 'resend_email' user.id %}">ここをクリック</a>してください。</p>
</body>
</html>

myapp/templates/error.html
<!-- templates/error.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
    <!-- Bootstrap CSS for styling -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .error-message {
            margin-top: 50px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12 error-message">
                <h2>Oops! Something went wrong.</h2>
                <!-- Show the error message passed from the view -->
                <p>Error: {{ error }}</p>
                <a href="/" class="btn btn-primary">Go to Home</a>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

myapp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        form {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
        }

        h2 {
            text-align: center;
            color: #333;
        }

        button {
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }

        .forgot-password {
            text-align: center;
            display: block;
            margin-top: 12px;
        }

        /* メディアクエリの追加 */
        @media (max-width: 600px) {
            body {
                background-color: #e7e7e7; /* 例として背景色を変更 */
            }

            form {
                width: 90%; /* フォームの幅を調整 */
                margin: 0 auto; /* 中央寄せ */
                padding: 10px; /* パディングを調整 */
            }

            button {
                padding: 10px 15px; /* ボタンのパディングを調整 */
            }

            /* 他の要素についても必要に応じてスタイルを調整 */
        }
        
    </style>
</head>
<body>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
        <a href="{% url 'password_reset' %}" class="forgot-password">パスワードを忘れた場合はこちら</a>


    </form>
 

</body>
</html>

myapp/templates/pre_signup.html
<!-- pre_signup.html -->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
        

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>新規登録 - MyV</title>
    <!-- スタイルシートへのリンク -->
    <link rel="stylesheet" href="{% static './css/pre_signup.css' %}">
</head>
<body>

    
      <header>
        <h1><a href="{% url 'home' %}">MyV</a></h1>
        <hr>
      </header>
      <hr>
    

    <main>
        <section>
            <h2>新規登録</h2>
            <section class="terms">
              <p>アカウントを作成することにより、<a href="terms_of_service.html">利用規約</a> および <a href="privacy_policy.html">プライバシーポリシー</a>に同意するものとします。</p>
          </section>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                
                <!-- カスタムエラーメッセージの表示 -->
                {% if error_message %}
                    <div class="error-message">
                        <p>{{ error_message }}</p>
                    </div>
                {% endif %}
                
                <button type="submit">事前登録</button>
            </form>

            {% if form.errors %}
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ field.label }}: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </section>

        <section class="signup">
            <p>すでにアカウントをお持ちですか？ <a href="login.html">ログイン</a></p>
        </section>
    </main>

    
      <footer>
        <p class="footer-copyright">
          © 2023 MyV. All Rights Reserved. Developed by TUSMUGI Yuri.
        </p>
      </footer>
    

    <!-- JavaScriptファイルへのリンク -->
    

</body>
</html>

myapp/templates/signup.html
<!-- signup.html -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">登録</button>
</form>

 

{% if form.errors %}
<ul>
    {% for field in form %}
        {% for error in field.errors %}
            <li>{{ error }}</li>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
    {% endfor %}
</ul>
{% endif %}